services:
  app:
    image: abbadev/symfo-test
    container_name: app_prod
    ports:
      - 127.0.0.1:3000:80
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}?serverVersion=16&charset=utf8"
      MAILER_DSN: ${MAILER_DSN}
      APP_ENV: prod

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    container_name: postgres_prod
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data: