FROM composer:2 AS builder
WORKDIR /app
COPY composer.json composer.lock ./
COPY . .
RUN composer install --no-dev


FROM php:8.2-apache
COPY --from=builder /app /var/www/html
COPY ./apache/virtualhost.conf /etc/apache2/sites-available/000-default.conf 

WORKDIR /var/www/html
RUN php bin/console asset-map:compile

RUN apt update \
&& apt install libpq-dev -y \
&& docker-php-ext-install pdo_pgsql pgsql \
&& rm -rf /var/lib/apt/lists/* \
&& apt clean

RUN chown -R www-data:www-data var/

# Expose the default HTTP port
EXPOSE 80