name: 'vps script action'
description: 'execute script in vps'
author: 'starsky & hutch'
inputs:
  ssh-private-key:
    description: 'private key ssh'
    required: true
  vps-username:
    description: 'vps username'
    required: true
  vps-host:
    description: 'vps hostname or ip address'
    required: true
  vps-path:
    description: 'the path on vps where the script will be executed'
    required: false
    default: ~/
  script:
    description: 'script to execute in vps'
    required: true
runs:
  using: 'composite'
  steps:
    - name: connexion vps
      uses: kielabokkie/ssh-key-and-known-hosts-action@v1
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}
        ssh-host: ${{ inputs.vps-host }}

    - name: connexion vps
      run: |
        ssh ${{ inputs.vps-username }}@${{ inputs.vps-host }} "cd ${{ inputs.vps-path }} && bash -s" < ${{ inputs.script }}
      shell: bash