name: update prod
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: xdebug

      - name: Install dependencies with composer
        run: composer update --no-ansi --no-interaction --no-progress

      - name: Run tests with phpunit/phpunit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml
        
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker-image:
    name: build docker image > docker hub
    runs-on: ubuntu-24.04
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build docker image
        run: docker build -f Dockerfile-prod -t ${{ secrets.DOCKERHUB_TAG }} .

      - name: connect DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

      - name: push docker image
        run: docker push ${{ secrets.DOCKERHUB_TAG }}

  vps:
    name: update vps
    runs-on: ubuntu-24.04
    needs: docker-image
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: connexion vps
        uses: ./github/actions/vps-script
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          vps-username: ${{ secrets.VPS_USERNAME }}
          vps-host: ${{ secrets.VPS_HOSTNAME }}
          vps-path: ${{ secrets.VPS_PATH }}
          script: ./vps-script.sh
