name: update prod
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: xdebug

      - name: Install dependencies with composer
        run: composer update --no-ansi --no-interaction --no-progress

      - name: Run tests with phpunit/phpunit
        run: vendor/bin/phpunit --coverage-clover=coverage.xml
        
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker-image:
    name: build docker image > docker hub
    runs-on: ubuntu-24.04
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: build docker image
        run: docker build -f Dockerfile-prod -t ${{ secrets.DOCKERHUB_TAG }} .

      - name: connect DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

      - name: push docker image
        run: docker push ${{ secrets.DOCKERHUB_TAG }}

  vps:
    name: update vps
    runs-on: ubuntu-24.04
    needs: docker-image
    steps:
      - name: connexion vps
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{ secrets.VPS_HOSTNAME }}

      - name: update docker image in VPS
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOSTNAME }} << EOF
          echo "Connexion reussie au VPS !!!"
          cd symfo-cicd/
          docker compose pull
          docker compose --env-file .env.prod up -d
          docker image prune -f
          echo "Mise à jour effectué avec succès le : `date`" >> log-update-app.txt
          exit
          EOF