name: update prod
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update:
    name: update vps docker network
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: build docker image
        run: docker build -f Dockerfile-prod -t ${{ secrets.DOCKERHUB_TAG }} .

      - name: connect DockerHub
        run: echo ${{ secrets.DOCKERHUB_PASS }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin

      - name: push docker image
        run: docker push ${{ secrets.DOCKERHUB_TAG }}

      - name: install sshpass
        run: sudo apt-get update && sudo apt-get install sshpass

      - name: update docker image in VPS
        run: |
          sshpass -p ${{ secrets.VPS_PASS }} ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOSTNAME }} << EOF
          echo "Connexion reussie au VPS !!!"
          cd symfo-cicd/
          docker compose up --env-file .env.prod --pull
          exit
          EOF